<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>media.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="media.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controls\" />
    <Folder Include="Tools\" />
    <Folder Include="Resources\" />
    <Folder Include="Utils\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Tools\ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Tools\yt-dlp.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>